version: '1'
services:
  tomcat:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./payload.ser:/tmp/payload.ser
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
    restart: unless-stopped
