# Docker Compose 버전 정의
version: '2'

# Docker Container 정의
services:
    mysql:
        image: vulhub/mysql:5.5.23  # vulhub/mysql 이미지 사용
        ports:
            - "3306:3306"   # host와 container의 port mapping