version: '3'

services:
  app:
    build: .
    container_name: vulnhub-CVE-2024-38474
    ports:
      - "8000:80"
    volumes:
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./phpinfo.php:/var/www/html/phpinfo
