version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CVE_2022_34265
    ports:
      - "5432:5432"

  web:
    image: python:3.10
    container_name: CVE-2022-34265
    volumes:
      - ./web:/usr/src
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./wait-for-it.sh:/wait-for-it.sh
    working_dir: /usr/src
    depends_on:
      - db
    ports:
      - "8000:8000"
    entrypoint: ["bash", "/docker-entrypoint.sh"]
    command:
      - python
      - app.py
      - runserver
      - 0.0.0.0:8000