version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-1
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - webnet
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: data

networks:
  webnet:
    driver: bridge

volumes:
  db-data:
    driver: local

