version: '2'
services:
  solr:
    image: vulhub/solr:8.11.0
    ports:
      - "8983:8983"

  attack: 
    image: antimony02/log4shell_jndi
    ports:
     - "8888:8888"
     - "1389:1389"

    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./init.sh:/Log4shell_JNDIExploit/init.sh
    command: bash -c "./init.sh"