version: '3'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      PHP_MEMORY_LIMIT: 512M
      UPLOAD_MAX_FILESIZE: 128M
      POST_MAX_SIZE: 128M
      MAX_EXECUTION_TIME: 300
    depends_on:
      - db

