services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["python3", "poc.py"]
    stdin_open: true
    tty: true