version: '2'
services:
 solr:
   container_name: log4shell_victim_mc
   image: justingarey/just-for-fun:exploitable-minecraft
   ports:
    - "25565:25565"
   ulimits:
      nofile:
         soft: "122880"
         hard: "122880"