version: "3.0"

services:
  app:
    container_name: CVE-2022-34265-pocTestapp
    build: ./
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: vuln
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  mysql:
    image: mysql:5.7
    platform: linux/amd64 # mac m1에서 실행시 필요
    container_name: CVE-2022-34265-mysql
    environment:
      MYSQL_ROOT_PASSWORD: vuln
      MYSQL_DATABASE: vuln
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pvuln"]
      timeout: 5s
      retries: 5
