version: '3' 

services: 
 db: 
  build: 
   context: .
   dockerfile: Dockerfile.db
  environment: 
   POSTGRES_PASSWORD: example
  volumes: 
   - pg_data:/var/lib/postgresql/data

 app: 
  build: 
   context: .
   dockerfile: Dockerfile.app
  ports: 
   - "5000:5000"
  depends_on: 
   - db 
   
volumes: 
 pg_data: 

