web:
  build: .
  environment:
    MYENV: EXAMPLE
  volumes:
    - .:/code
web_migrate:
  extends:
    service: web
  command: python3 manage.py migrate
web_run:
  extends:
    service: web
  command: python3 manage.py runserver 0:3000
  ports:
    - "3000:3000"