version: '3.2'

services:

  nginx:
    image: namelessmc/nginx:v2.1.3
    ports: ['8080:8080']
    volumes:
      - type: bind # same as php container
        source: ./web
        target: /data
    # environment: # Change this if you rename the php container
    #   PHP_FPM: php:9000
    # user: 'youruser'
    depends_on: [php]
    # restart: always

  php:
    image: namelessmc/php:v2.1.3
    volumes:
      - type: bind # same as web container
        source: ./web
        target: /data
    depends_on: [db]
    # user: 'youruser'
    # restart: always

  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/mysql
      - ./contents/sys.sql:/docker-entrypoint-initdb.d/sys.sql
      - ./contents/nameless.sql:/docker-entrypoint-initdb.d/nameless.sql
    environment:
      MARIADB_ROOT_PASSWORD: nameless
      MARIADB_USER: nameless
      MARIADB_PASSWORD: nameless
      MARIADB_DATABASE: nameless
      MARIADB_AUTO_UPGRADE: 1
    # restart: always

